include:
  - docker-compose-mongo.yaml

services:
  reservations:
    container_name: air-cnc-reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
