version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data_config:/data/configdb
  # Comment out the service if web gui is not needed
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  mongodb_data_config:
