version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_data_config:
